language: python
python:
  - "3.5"
  - "3.6"
  - "3.5-dev"
  - "3.6-dev"
install:
  - pip3 install -r requirements.txt
  - pip3 install coverage
  - pip3 install twine

script:
  - python3 setup.py test

  
