language: python
branches:
  only:
  - master
  - stable
python:
- '3.8'
install:
- pip3 install -r requirements.txt
- pip3 install python-coveralls
- pip3 install coverage
- pip3 install twine
script:
- coverage run --source outfit setup.py test
- python3 setup.py sdist bdist_wheel
after_success:
- coveralls
deploy:
  skip_cleanup: true
  provider: pypi
  user: situkangsayur
  password:
    secure: URar7+kTFaehxrIJOzW12ym9t/h0JXBAz0i7dmxkgRTKObEBTWnsjL0fFkFD8UNrRayYlVRllFG0H8fnkxlNda2sgyYS1kymKMkl5oTs/2bmAWJEu6W2CgTQgrLp+D0fjnqXpnUjpxVCO2B2J+HNw0UyG22FWiOg6zZpT8dufCneBCUSboeJjrwXATzyW7cCAl29GSXegitn+67cJ0ns7g+AU76gfbtlD90KPyY/Og9lAvIF/BrVt4qY2krCIj4263cNc1WDFnDDqney+csrVE27UaBzo1Plrug52NJQcCUy+Bnu9oRn3O47mzNOba603JQ/Sa3kMx+HViFLKlnl/eqVMN2/F/dSFso467uS8CokuBq3Hf9y8z3XbWRlJPMWRtkBlWke7rKOSR78PhNKwZm2MEOo1gjoX5yIeKjTbWWyCcDmCu1pJwiz0G3lt7K3dQl9Nsv+ZSimX8IMx7N/T3PtoaRAEhlkZ0MOMweeec8waf/tdc9QaqUBqziDK/JQPkwOJdSLA3LSx2ypOFUbUXqQ2sF4XxX5Ik+eFw04SajUOT8A9L6MiwwaxukYjFM5qGO5k5BM9b4mUy4WKoLJcr9kaLLswYrbjfv46+voPAFGNTyHJ6qkiVcTnfaPkNJUjozLH2DhsokrFG4bKZVXtl7zfxha/N7K+hwotmt3a6Y=
  distributions: sdist bdist_wheel
