language: python
branches:
  only:
  - master
  - stable
python:
- '3.8'
install:
- pip3 install -r requirements.txt
- pip3 install python-coveralls
- pip3 install coverage
- pip3 install twine
script:
- coverage run --source outfit setup.py test
- python3 setup.py sdist bdist_wheel
after_success:
- coveralls
deploy:
  skip_cleanup: true
  provider: pypi
  user: situkangsayur
  password:
    secure: S3XNopk+YvshTKWQz5hzJMdUPocL0k0Ml1DBhBlLnmAN22vLm2D7En0SguTPdjYeSGdPnwBnzRy9CGRlvNKDGwk5p+1Hnp8PXxcdSxEvKWGtsUxFV8yru/ZPi08LXFYP2m6Ka8n0ZF1jFX6DAgkLXa12MqmczjZP22NEi3vKRG8uMsSdNSYU5gKDBZpn3nSpF2UgDTxs0/Pi+CUgrA+Na5UHFMWnNj051HiAxNoBq1tprQejvLRKUJx9504nC1+5lxVvm3gNBrE+5h50qOl3DQqDaNiktPAEr5oC6Qbg3sGyaP3lRHT2cZ8gZn19BEQz5DSA9QDWkOpYi5swZnoKTdViyKnztjUJmCIGpj5uHQ8wtJTGeiOIjSdjpQfnfU8JK390LRDUFAoTdGz3I8WGt6OPCb1W6LIMWhoaVbV5GRWOpCwx4B5lVkMqf0AAFxLHPW7qCKfSCMn4G2THYt2ODLvk4Kq1tFKC6YdouL5Ss39JoLILtnJo7TddCxKY3RepSs3F3jfke/1zDBKrjobRx/3C/czLkIxHs3Zh3Zp1P6ZgUBuhJi9p7W0PUDeUaIQJQKNr9sYkQrsSId/5DDrXdKdqO2BkKQVJePbb9BITFnFRI7iRlQ5yWoylGnPpUzgAc4VaPCEOLHYZPy/y2EKVxF0bYDVACXk7dv6nM/FcdZs=
  distributions: sdist bdist_wheel
