language: python
branches:
  only:
  - master
  - stable
python:
- '3.8'
install:
- pip3 install -r requirements.txt
- pip3 install python-coveralls
- pip3 install coverage
- pip3 install twine
script:
- coverage run --source outfit setup.py test
- python3 setup.py sdist bdist_wheel
after_success:
- coveralls
deploy:
  skip_cleanup: true
  provider: pypi
  user: situkangsayur
  password:
    secure: WR2hE1TqA0YRpAlbRyAJJRXT+lcO9b42MP9Kld7Ktaf/wyMvN/nld7bGSEDHYJVzBOg8EZ/e0Gq1ZEF+WcINy/fjNYQgefEw1TpNhoUc3zX/cQNfyTq35vpxGDx+yFvuKYy8RKbVgFreCsMulYh6eefeCVjXrYMkRSub+H8oCOW88lgsVMa+3CggxzmTzoHn0bcjav5mYIpY2eYvpnrSYjU1jJXpfwNSuyh7wPKy8EmG/b9zFnkwZe2PU6CrhIrPx7dp6ptnshOslFuS1I5DxQuu1sXGOcvMX7P+0MQzEoQbHb/Y2hNjAJItM0uqeZuoFv7EphV6yv9SkVw9b83NQP+0tcWbsx3n1ARNu3QybP+UEWN18/39nOpl4gqTEgEs8P0pUvPniqc7WN1mi4suGhv2++NPQSOVEFK4mM7aSIg4N+f/JSSLhV0cKrTfXhRoyJzU15ljt8uUacYKFzfs1XtFnifTGPBkBVrbCKp18oxPHLIfxObxOcyNGmnrANpeIr91rK7ofRBCvkdS1tF5S8nMCI0JhNcE/CXKBWjQY+ql9ag2VfWXL3tGfnrEh8Pp4DLjmWOAyZJEpqkOs4y8tYkcZgkuyY1YLm3+PT8Yzj9ZG+AOWEkdM1iJazyY9AaB64HtRe6lxVj3lHX7/lamoUD5DSwDpD3p0I9YaY52UEk=
  distributions: sdist bdist_wheel
